export interface PropertyConfig {
    Id:number;
    isPropertyType:boolean;
    isBhk:boolean; 
    ageOfProperty:boolean;
    maintainCharge:boolean;
    bathRoom:boolean;
    balcony: boolean;
    furnishType: boolean;
    coverParking: boolean;
    openParking: boolean;
    tenantType: boolean;
    availableFrom: boolean;
    monthlyRent: boolean;
    securityDeposite: boolean;
    brokerage: boolean;
    buildArea: boolean;
    transactionType: boolean;
    constructionStatus: boolean;
    pGName: boolean;
    totalBed: boolean;
    pgFor: boolean;
    suitedFor: boolean;
    mealAvalable: boolean;
    carpetArea: boolean;
    roomType:boolean;
    bedInRoom: boolean;
    pgRent: boolean;
    securityType: boolean;
    facilitiesOffered: boolean;
    commonAreas: boolean;
    propertyManagedBy: boolean;
    nonVegAllowed:boolean;
    oppositeSexAllowed:boolean;
    anyTimeAllowed:boolean;
    visitorsAllowed:boolean;
    guardianAllowed:boolean;
    drinkingAllowed:boolean;
    smokingAllowed:boolean;
}